package io.github.joppebijlsma.tvstudio.registries;

import io.github.joppebijlsma.tvstudio.blocks.DirectorChair;
import io.github.joppebijlsma.tvstudio.blocks.SetWall;
import io.github.joppebijlsma.tvstudio.blocks.SetWallSupport;
import io.github.joppebijlsma.tvstudio.blocks.StudioBar;
import io.github.joppebijlsma.tvstudio.blocks.StudioLight;
import io.github.joppebijlsma.tvstudio.blocks.TvCamera;
import io.github.joppebijlsma.tvstudio.blocks.TvCameraOnAStand;
import io.github.joppebijlsma.tvstudio.blocks.TvStand;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.Material;
import net.minecraft.block.WallBlock;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class ModBlocks {

		//screen blocks
		public static final Block BLUE_SCREEN_BLOCK =  new Block(AbstractBlock.Settings.of(Material.STONE).breakInstantly().sounds(BlockSoundGroup.STONE));
		public static final Block GREEN_SCREEN_BLOCK = new Block(AbstractBlock.Settings.of(Material.STONE).breakInstantly().sounds(BlockSoundGroup.STONE));
		public static final Block GREEN_SCREEN_WALL = new WallBlock(AbstractBlock.Settings.of(Material.WOOL).breakInstantly().sounds(BlockSoundGroup.METAL));
		public static final Block BLUE_SCREEN_WALL = new WallBlock(AbstractBlock.Settings.of(Material.WOOL).breakInstantly().sounds(BlockSoundGroup.METAL));
		
		//non coloured 
		public static final Block TV_CAMERA = new TvCamera();
		public static final Block CHIPBOARD_BLOCK = new Block(AbstractBlock.Settings.of(Material.WOOD).strength(3f, 3f).sounds(BlockSoundGroup.WOOD));
		public static final Block SET_WALL_SUPPORT = new SetWallSupport();
		
		//Coloured
		//TV Camera On A Stand
		public static final Block WHITE_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block ORANGE_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block MAGENTA_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block LIGHT_BLUE_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block YELLOW_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block LIME_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block PINK_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block GRAY_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block LIGHT_GRAY_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block CYAN_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block PURPLE_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block BLUE_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block BROWN_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block GREEN_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block RED_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		public static final Block BLACK_TV_CAMERA_ON_STAND = new TvCameraOnAStand();
		
		//Tv Stand
		public static final Block WHITE_TV_STAND = new TvStand();
		public static final Block ORANGE_TV_STAND = new TvStand();
		public static final Block MAGENTA_TV_STAND = new TvStand();
		public static final Block LIGHT_BLUE_TV_STAND = new TvStand();
		public static final Block YELLOW_TV_STAND = new TvStand();
		public static final Block LIME_TV_STAND = new TvStand();
		public static final Block PINK_TV_STAND = new TvStand();
		public static final Block GRAY_TV_STAND = new TvStand();
		public static final Block LIGHT_GRAY_TV_STAND = new TvStand();
		public static final Block CYAN_TV_STAND = new TvStand();
		public static final Block PURPLE_TV_STAND = new TvStand();
		public static final Block BLUE_TV_STAND = new TvStand();
		public static final Block BROWN_TV_STAND = new TvStand();
		public static final Block GREEN_TV_STAND = new TvStand();
		public static final Block RED_TV_STAND = new TvStand();
		public static final Block BLACK_TV_STAND = new TvStand();
		
		//Studio Light
		public static final Block WHITE_STUDIO_LIGHT = new StudioLight();
		public static final Block ORANGE_STUDIO_LIGHT = new StudioLight();
		public static final Block MAGENTA_STUDIO_LIGHT = new StudioLight();
		public static final Block LIGHT_BLUE_STUDIO_LIGHT = new StudioLight();
		public static final Block YELLOW_STUDIO_LIGHT = new StudioLight();
		public static final Block LIME_STUDIO_LIGHT = new StudioLight();
		public static final Block PINK_STUDIO_LIGHT = new StudioLight();
		public static final Block GRAY_STUDIO_LIGHT = new StudioLight();
		public static final Block LIGHT_GRAY_STUDIO_LIGHT = new StudioLight();
		public static final Block CYAN_STUDIO_LIGHT = new StudioLight();
		public static final Block PURPLE_STUDIO_LIGHT = new StudioLight();
		public static final Block BLUE_STUDIO_LIGHT = new StudioLight();
		public static final Block BROWN_STUDIO_LIGHT = new StudioLight();
		public static final Block GREEN_STUDIO_LIGHT = new StudioLight();
		public static final Block RED_STUDIO_LIGHT = new StudioLight();
		public static final Block BLACK_STUDIO_LIGHT = new StudioLight();
		
		//Studio Bar
		public static final Block WHITE_STUDIO_BAR = new StudioBar();
		public static final Block ORANGE_STUDIO_BAR = new StudioBar();
		public static final Block MAGENTA_STUDIO_BAR = new StudioBar();
		public static final Block LIGHT_BLUE_STUDIO_BAR = new StudioBar();
		public static final Block YELLOW_STUDIO_BAR = new StudioBar();
		public static final Block LIME_STUDIO_BAR = new StudioBar();
		public static final Block PINK_STUDIO_BAR = new StudioBar();
		public static final Block GRAY_STUDIO_BAR = new StudioBar();
		public static final Block LIGHT_GRAY_STUDIO_BAR = new StudioBar();
		public static final Block CYAN_STUDIO_BAR = new StudioBar();
		public static final Block PURPLE_STUDIO_BAR = new StudioBar();
		public static final Block BLUE_STUDIO_BAR = new StudioBar();
		public static final Block BROWN_STUDIO_BAR = new StudioBar();
		public static final Block GREEN_STUDIO_BAR = new StudioBar();
		public static final Block RED_STUDIO_BAR = new StudioBar();
		public static final Block BLACK_STUDIO_BAR = new StudioBar();
		
		//Director Chair
		public static final Block WHITE_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block ORANGE_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block MAGENTA_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block LIGHT_BLUE_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block YELLOW_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block LIME_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block PINK_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block GRAY_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block LIGHT_GRAY_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block CYAN_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block PURPLE_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block BLUE_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block BROWN_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block GREEN_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block RED_DIRECTOR_CHAIR = new DirectorChair();
		public static final Block BLACK_DIRECTOR_CHAIR = new DirectorChair();

		//Set
		public static final Block SET_WALL = new SetWall();
		public static final Block SET_WALL_STONE = new SetWall();
		public static final Block SET_WALL_GRANITE = new SetWall();
		public static final Block SET_WALL_POLISHED_GRANITE = new SetWall();
		public static final Block SET_WALL_DIORITE = new SetWall();
		public static final Block SET_WALL_POLISHED_DIORITE = new SetWall();
		public static final Block SET_WALL_ANDESITE = new SetWall();
		public static final Block SET_WALL_POLISHED_ANDESITE = new SetWall();
		public static final Block SET_WALL_DIRT = new SetWall();
		public static final Block SET_WALL_COARSE_DIRT = new SetWall();
		public static final Block SET_WALL_CRIMSON_NYLIUM = new SetWall();
		public static final Block SET_WALL_WARPED_NYLIUM = new SetWall();
		public static final Block SET_WALL_COBBLESTONE = new SetWall();
		public static final Block SET_WALL_OAK_PLANKS = new SetWall();
		public static final Block SET_WALL_SPRUCE_PLANKS = new SetWall();
		public static final Block SET_WALL_BIRCH_PLANKS = new SetWall();
		public static final Block SET_WALL_JUNGLE_PLANKS = new SetWall();
		public static final Block SET_WALL_ACACIA_PLANKS = new SetWall();
		public static final Block SET_WALL_DARK_OAK_PLANKS = new SetWall();
		public static final Block SET_WALL_CRIMSON_PLANKS = new SetWall();
		public static final Block SET_WALL_WARPED_PLANKS = new SetWall();
		public static final Block SET_WALL_BEDROCK = new SetWall();
		public static final Block SET_WALL_SAND = new SetWall();
		public static final Block SET_WALL_RED_SAND = new SetWall();
		public static final Block SET_WALL_GRAVEL = new SetWall();
		public static final Block SET_WALL_GOLD_ORE = new SetWall();
		public static final Block SET_WALL_IRON_ORE = new SetWall();
		public static final Block SET_WALL_COAL_ORE = new SetWall();
		public static final Block SET_WALL_NETHER_GOLD_ORE = new SetWall();
		public static final Block SET_WALL_OAK_LOG = new SetWall();
		public static final Block SET_WALL_SPRUCE_LOG = new SetWall();
		public static final Block SET_WALL_BIRCH_LOG = new SetWall();
		public static final Block SET_WALL_JUNGLE_LOG = new SetWall();
		public static final Block SET_WALL_ACACIA_LOG = new SetWall();
		public static final Block SET_WALL_DARK_OAK_LOG = new SetWall();
		public static final Block SET_WALL_CRIMSON_STEM = new SetWall();
		public static final Block SET_WALL_WARPED_STEM = new SetWall();
		public static final Block SET_WALL_STRIPPED_OAK_LOG = new SetWall();
		public static final Block SET_WALL_STRIPPED_SPRUCE_LOG = new SetWall();
		public static final Block SET_WALL_STRIPPED_BIRCH_LOG = new SetWall();
		public static final Block SET_WALL_STRIPPED_JUNGLE_LOG = new SetWall();
		public static final Block SET_WALL_STRIPPED_ACACIA_LOG = new SetWall();
		public static final Block SET_WALL_STRIPPED_DARK_OAK_LOG = new SetWall();
		public static final Block SET_WALL_STRIPPED_CRIMSON_STEM = new SetWall();
		public static final Block SET_WALL_STRIPPED_WARPED_STEM = new SetWall();
		public static final Block SET_WALL_SPONGE = new SetWall();
		public static final Block SET_WALL_WET_SPONGE = new SetWall();
		public static final Block SET_WALL_LAPIS_ORE = new SetWall();
		public static final Block SET_WALL_LAPIS_BLOCK = new SetWall();
		public static final Block SET_WALL_DISPENSER = new SetWall();
		public static final Block SET_WALL_SANDSTONE = new SetWall();
		public static final Block SET_WALL_CHISELED_SANDSTONE = new SetWall();
		public static final Block SET_WALL_CUT_SANDSTONE = new SetWall();
		public static final Block SET_WALL_NOTE_BLOCK = new SetWall();
		public static final Block SET_WALL_WHITE_WOOL = new SetWall();
		public static final Block SET_WALL_ORANGE_WOOL = new SetWall();
		public static final Block SET_WALL_MAGENTA_WOOL = new SetWall();
		public static final Block SET_WALL_LIGHT_BLUE_WOOL = new SetWall();
		public static final Block SET_WALL_YELLOW_WOOL = new SetWall();
		public static final Block SET_WALL_LIME_WOOL = new SetWall();
		public static final Block SET_WALL_PINK_WOOL = new SetWall();
		public static final Block SET_WALL_GRAY_WOOL = new SetWall();
		public static final Block SET_WALL_LIGHT_GRAY_WOOL = new SetWall();
		public static final Block SET_WALL_CYAN_WOOL = new SetWall();
		public static final Block SET_WALL_PURPLE_WOOL = new SetWall();
		public static final Block SET_WALL_BLUE_WOOL = new SetWall();
		public static final Block SET_WALL_BROWN_WOOL = new SetWall();
		public static final Block SET_WALL_GREEN_WOOL = new SetWall();
		public static final Block SET_WALL_RED_WOOL = new SetWall();
		public static final Block SET_WALL_BLACK_WOOL = new SetWall();
		public static final Block SET_WALL_GOLD_BLOCK = new SetWall();
		public static final Block SET_WALL_IRON_BLOCK = new SetWall();
		public static final Block SET_WALL_SMOOTH_QUARTZ = new SetWall();
		public static final Block SET_WALL_SMOOTH_RED_SANDSTONE = new SetWall();
		public static final Block SET_WALL_SMOOTH_SANDSTONE = new SetWall();
		public static final Block SET_WALL_SMOOTH_STONE = new SetWall();		
		public static final Block SET_WALL_BRICKS = new SetWall();
		public static final Block SET_WALL_TNT = new SetWall();
		public static final Block SET_WALL_BOOKSHELF = new SetWall();
		public static final Block SET_WALL_MOSSY_COBBLESTONE = new SetWall();
		public static final Block SET_WALL_OBSIDIAN = new SetWall();
		public static final Block SET_WALL_PURPUR_BLOCK = new SetWall();
		public static final Block SET_WALL_PURPUR_PILLAR = new SetWall();
		public static final Block SET_WALL_DIAMOND_ORE = new SetWall();
		public static final Block SET_WALL_DIAMOND_BLOCK = new SetWall();
		public static final Block SET_WALL_REDSTONE_ORE = new SetWall();
		public static final Block SET_WALL_ICE = new SetWall();
		public static final Block SET_WALL_SNOW_BLOCK = new SetWall();
		public static final Block SET_WALL_CLAY = new SetWall();
		public static final Block SET_WALL_JUKEBOX = new SetWall();
		public static final Block SET_WALL_PUMPKIN = new SetWall();
		public static final Block SET_WALL_CARVED_PUMPKIN = new SetWall();
		public static final Block SET_WALL_SOUL_SAND = new SetWall();
		public static final Block SET_WALL_SOUL_SOIL = new SetWall();
		public static final Block SET_WALL_BASALT = new SetWall();
		public static final Block SET_WALL_BASALT_TOP = new SetWall();
		public static final Block SET_WALL_POLISHED_BASALT = new SetWall();
		public static final Block SET_WALL_POLISHED_BASALT_TOP = new SetWall();
		public static final Block SET_WALL_GLOWSTONE = new SetWall();
		public static final Block SET_WALL_STONE_BRICKS = new SetWall();
		public static final Block SET_WALL_MOSSY_STONE_BRICKS = new SetWall();
		public static final Block SET_WALL_CRACKED_STONE_BRICKS = new SetWall();
		public static final Block SET_WALL_CHISELED_STONE_BRICKS = new SetWall();
		public static final Block SET_WALL_BROWN_MUSHROOM_BLOCK = new SetWall();
		public static final Block SET_WALL_RED_MUSHROOM_BLOCK = new SetWall();
		public static final Block SET_WALL_MUSHROOM_INSIDE = new SetWall();
		public static final Block SET_WALL_MUSHROOM_STEM = new SetWall();
		public static final Block SET_WALL_MELON = new SetWall();
		public static final Block SET_WALL_MELON_TOP = new SetWall();
		public static final Block SET_WALL_NETHER_BRICKS = new SetWall();
		public static final Block SET_WALL_CRACKED_NETHER_BRICKS = new SetWall();
		public static final Block SET_WALL_CHISELED_NETHER_BRICKS = new SetWall();
		public static final Block SET_WALL_END_STONE = new SetWall();
		public static final Block SET_WALL_END_STONE_BRICKS = new SetWall();
		public static final Block SET_WALL_EMERALD_ORE = new SetWall();
		public static final Block SET_WALL_EMERALD_BLOCK = new SetWall();
		public static final Block SET_WALL_REDSTONE_BLOCK = new SetWall();
		public static final Block SET_WALL_NETHER_QUARTZ_ORE = new SetWall();
		public static final Block SET_WALL_CHISELED_QUARTZ_BLOCK = new SetWall();
		public static final Block SET_WALL_QUARTZ_BLOCK = new SetWall();
		public static final Block SET_WALL_QUARTZ_BRICKS = new SetWall();
		public static final Block SET_WALL_QUARTZ_PILLAR = new SetWall();
		public static final Block SET_WALL_WHITE_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_ORANGE_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_MAGENTA_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_LIGHT_BLUE_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_YELLOW_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_LIME_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_PINK_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_GRAY_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_LIGHT_GRAY_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_CYAN_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_PURPLE_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_BLUE_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_BROWN_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_GREEN_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_RED_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_BLACK_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_HAY_BLOCK = new SetWall();
		public static final Block SET_WALL_HAY_BLOCK_TOP = new SetWall();
		public static final Block SET_WALL_TERRACOTTA = new SetWall();
		public static final Block SET_WALL_COAL_BLOCK = new SetWall();
		public static final Block SET_WALL_PACKED_ICE = new SetWall();
		public static final Block SET_WALL_PRISMARINE = new SetWall();
		public static final Block SET_WALL_PRISMARINE_BRICKS = new SetWall();
		public static final Block SET_WALL_DARK_PRISMARINE = new SetWall();
		public static final Block SET_WALL_SEA_LANTERN = new SetWall();
		public static final Block SET_WALL_RED_SANDSTONE = new SetWall();
		public static final Block SET_WALL_CHISELED_RED_SANDSTONE = new SetWall();
		public static final Block SET_WALL_CUT_RED_SANDSTONE = new SetWall();
		public static final Block SET_WALL_MAGMA_BLOCK = new SetWall();
		public static final Block SET_WALL_NETHER_WART_BLOCK = new SetWall();
		public static final Block SET_WALL_WARPED_WART_BLOCK = new SetWall();
		public static final Block SET_WALL_RED_NETHER_BRICKS = new SetWall();
		public static final Block SET_WALL_BONE_BLOCK = new SetWall();
		public static final Block SET_WALL_OBSERVER = new SetWall();
		public static final Block SET_WALL_WHITE_CONCRETE = new SetWall();
		public static final Block SET_WALL_ORANGE_CONCRETE = new SetWall();
		public static final Block SET_WALL_MAGENTA_CONCRETE = new SetWall();
		public static final Block SET_WALL_LIGHT_BLUE_CONCRETE = new SetWall();
		public static final Block SET_WALL_YELLOW_CONCRETE = new SetWall();
		public static final Block SET_WALL_LIME_CONCRETE = new SetWall();
		public static final Block SET_WALL_PINK_CONCRETE = new SetWall();
		public static final Block SET_WALL_GRAY_CONCRETE = new SetWall();
		public static final Block SET_WALL_LIGHT_GRAY_CONCRETE = new SetWall();
		public static final Block SET_WALL_CYAN_CONCRETE = new SetWall();
		public static final Block SET_WALL_PURPLE_CONCRETE = new SetWall();
		public static final Block SET_WALL_BLUE_CONCRETE = new SetWall();
		public static final Block SET_WALL_BROWN_CONCRETE = new SetWall();
		public static final Block SET_WALL_GREEN_CONCRETE = new SetWall();
		public static final Block SET_WALL_RED_CONCRETE = new SetWall();
		public static final Block SET_WALL_BLACK_CONCRETE = new SetWall();
		public static final Block SET_WALL_WHITE_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_ORANGE_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_MAGENTA_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_LIGHT_BLUE_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_YELLOW_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_LIME_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_PINK_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_GRAY_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_LIGHT_GRAY_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_CYAN_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_PURPLE_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_BLUE_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_BROWN_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_GREEN_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_RED_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_BLACK_CONCRETE_POWDER = new SetWall();
		public static final Block SET_WALL_DEAD_TUBE_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_DEAD_BRAIN_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_DEAD_BUBBLE_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_DEAD_FIRE_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_DEAD_HORN_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_TUBE_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_BRAIN_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_BUBBLE_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_FIRE_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_HORN_CORAL_BLOCK = new SetWall();
		public static final Block SET_WALL_BLUE_ICE = new SetWall();
		public static final Block SET_WALL_DRIED_KELP_BLOCK = new SetWall();
		public static final Block SET_WALL_COMPOSTER = new SetWall();
		public static final Block SET_WALL_SMITHING_TABLE_TOP = new SetWall();
		public static final Block SET_WALL_SMITHING_TABLE_BOTTOM = new SetWall();
		public static final Block SET_WALL_SHROOMLIGHT = new SetWall();
		public static final Block SET_WALL_BEE_NEST = new SetWall();
		public static final Block SET_WALL_BEEHIVE = new SetWall();
		public static final Block SET_WALL_HONEYCOMB_BLOCK = new SetWall();
		public static final Block SET_WALL_LODESTONE = new SetWall();
		public static final Block SET_WALL_LODESTONE_TOP = new SetWall();
		public static final Block SET_WALL_NETHERITE_BLOCK = new SetWall();
		public static final Block SET_WALL_ANCIENT_DEBRIS = new SetWall();
		public static final Block SET_WALL_TARGET = new SetWall();
		public static final Block SET_WALL_CRYING_OBSIDIAN = new SetWall();
		public static final Block SET_WALL_NETHERRACK = new SetWall();
		public static final Block SET_WALL_BLACKSTONE = new SetWall();
		public static final Block SET_WALL_POLISHED_BLACKSTONE_BRICKS = new SetWall();
		public static final Block SET_WALL_GILDED_BLACKSTONE = new SetWall();
		public static final Block SET_WALL_POLISHED_BLACKSTONE = new SetWall();
		public static final Block SET_WALL_CHISELED_POLISHED_BLACKSTONE = new SetWall();
		public static final Block SET_WALL_CRACKED_POLISHED_BLACKSTONE_BRICKS = new SetWall();		
		public static final Block SET_WALL_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_WHITE_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_ORANGE_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_MAGENTA_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_LIGHT_BLUE_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_YELLOW_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_LIME_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_PINK_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_GRAY_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_LIGHT_GRAY_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_CYAN_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_PURPLE_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_BLUE_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_BROWN_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_GREEN_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_RED_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_BLACK_SHULKER_BOX = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_GOLD_ORE = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_IRON_ORE = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_COAL_ORE = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_LAPIS_ORE = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_DIAMOND_ORE = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_REDSTONE_ORE = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_EMERALD_ORE = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_COPPER_ORE = new SetWall();
		public static final Block SET_WALL_AZALEA = new SetWall();
		public static final Block SET_WALL_FLOWERING_AZALEA = new SetWall();
		public static final Block SET_WALL_MOSS_BLOCK = new SetWall();
		public static final Block SET_WALL_ROOTED_DIRT = new SetWall();
		public static final Block SET_WALL_AMETHYST_BLOCK = new SetWall();	
		public static final Block SET_WALL_BUDDING_AMETHYST = new SetWall();
		public static final Block SET_WALL_TUFF = new SetWall();
		public static final Block SET_WALL_CALCITE = new SetWall();
		public static final Block SET_WALL_POWDER_SNOW = new SetWall();
		public static final Block SET_WALL_OXIDIZED_COPPER = new SetWall();
		public static final Block SET_WALL_WEATHERED_COPPER = new SetWall();
		public static final Block SET_WALL_EXPOSED_COPPER = new SetWall();
		public static final Block SET_WALL_COPPER_BLOCK = new SetWall();
		public static final Block SET_WALL_COPPER_ORE = new SetWall();
		public static final Block SET_WALL_OXIDIZED_CUT_COPPER = new SetWall();
		public static final Block SET_WALL_WEATHERED_CUT_COPPER = new SetWall();
		public static final Block SET_WALL_EXPOSED_CUT_COPPER = new SetWall();
		public static final Block SET_WALL_CUT_COPPER = new SetWall();
		public static final Block SET_WALL_DRIPSTONE_BLOCK = new SetWall();
		public static final Block SET_WALL_DEEPSLATE = new SetWall();
		public static final Block SET_WALL_COBBLED_DEEPSLATE = new SetWall();
		public static final Block SET_WALL_POLISHED_DEEPSLATE = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_TILES = new SetWall();
		public static final Block SET_WALL_DEEPSLATE_BRICKS = new SetWall();
		public static final Block SET_WALL_CHISELED_DEEPSLATE = new SetWall();
		public static final Block SET_WALL_CRACKED_DEEPSLATE_BRICKS = new SetWall();
		public static final Block SET_WALL_CRACKED_DEEPSLATE_TILES = new SetWall();
		public static final Block SET_WALL_SMOOTH_BASALT = new SetWall();
		public static final Block SET_WALL_RAW_IRON_BLOCK = new SetWall();
		public static final Block SET_WALL_RAW_COPPER_BLOCK = new SetWall();
		public static final Block SET_WALL_RAW_GOLD_BLOCK = new SetWall();
		
	public static void register() {
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "blue_screen_block"), BLUE_SCREEN_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "green_screen_block"), GREEN_SCREEN_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "green_screen_wall"), GREEN_SCREEN_WALL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "blue_screen_wall"), BLUE_SCREEN_WALL);	
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "tv_camera"), TV_CAMERA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "chipboard_block"), CHIPBOARD_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_support"), SET_WALL_SUPPORT);	
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "white_tv_camera_on_stand"), WHITE_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "orange_tv_camera_on_stand"), ORANGE_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "magenta_tv_camera_on_stand"), MAGENTA_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_blue_tv_camera_on_stand"), LIGHT_BLUE_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "yellow_tv_camera_on_stand"), YELLOW_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "lime_tv_camera_on_stand"), LIME_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "pink_tv_camera_on_stand"), PINK_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "gray_tv_camera_on_stand"), GRAY_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_gray_tv_camera_on_stand"), LIGHT_GRAY_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "cyan_tv_camera_on_stand"), CYAN_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "purple_tv_camera_on_stand"), PURPLE_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "blue_tv_camera_on_stand"), BLUE_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "brown_tv_camera_on_stand"), BROWN_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "green_tv_camera_on_stand"), GREEN_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "red_tv_camera_on_stand"), RED_TV_CAMERA_ON_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "black_tv_camera_on_stand"), BLACK_TV_CAMERA_ON_STAND);		
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "white_tv_stand"), WHITE_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "orange_tv_stand"), ORANGE_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "magenta_tv_stand"), MAGENTA_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_blue_tv_stand"), LIGHT_BLUE_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "yellow_tv_stand"), YELLOW_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "lime_tv_stand"), LIME_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "pink_tv_stand"), PINK_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "gray_tv_stand"), GRAY_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_gray_tv_stand"), LIGHT_GRAY_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "cyan_tv_stand"), CYAN_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "purple_tv_stand"), PURPLE_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "blue_tv_stand"), BLUE_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "brown_tv_stand"), BROWN_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "green_tv_stand"), GREEN_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "red_tv_stand"), RED_TV_STAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "black_tv_stand"), BLACK_TV_STAND);		
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "white_studio_light"), WHITE_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "orange_studio_light"), ORANGE_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "magenta_studio_light"), MAGENTA_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_blue_studio_light"), LIGHT_BLUE_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "yellow_studio_light"), YELLOW_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "lime_studio_light"), LIME_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "pink_studio_light"), PINK_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "gray_studio_light"), GRAY_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_gray_studio_light"), LIGHT_GRAY_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "cyan_studio_light"), CYAN_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "purple_studio_light"), PURPLE_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "blue_studio_light"), BLUE_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "brown_studio_light"), BROWN_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "green_studio_light"), GREEN_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "red_studio_light"), RED_STUDIO_LIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "black_studio_light"), BLACK_STUDIO_LIGHT);		
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "white_studio_bar"), WHITE_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "orange_studio_bar"), ORANGE_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "magenta_studio_bar"), MAGENTA_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_blue_studio_bar"), LIGHT_BLUE_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "yellow_studio_bar"), YELLOW_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "lime_studio_bar"), LIME_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "pink_studio_bar"), PINK_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "gray_studio_bar"), GRAY_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_gray_studio_bar"), LIGHT_GRAY_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "cyan_studio_bar"), CYAN_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "purple_studio_bar"), PURPLE_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "blue_studio_bar"), BLUE_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "brown_studio_bar"), BROWN_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "green_studio_bar"), GREEN_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "red_studio_bar"), RED_STUDIO_BAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "black_studio_bar"), BLACK_STUDIO_BAR);		
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "white_director_chair"), WHITE_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "orange_director_chair"), ORANGE_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "magenta_director_chair"), MAGENTA_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_blue_director_chair"), LIGHT_BLUE_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "yellow_director_chair"), YELLOW_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "lime_director_chair"), LIME_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "pink_director_chair"), PINK_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "gray_director_chair"), GRAY_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "light_gray_director_chair"), LIGHT_GRAY_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "cyan_director_chair"), CYAN_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "purple_director_chair"), PURPLE_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "blue_director_chair"), BLUE_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "brown_director_chair"), BROWN_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "green_director_chair"), GREEN_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "red_director_chair"), RED_DIRECTOR_CHAIR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "black_director_chair"), BLACK_DIRECTOR_CHAIR);		
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall"), SET_WALL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stone"), SET_WALL_STONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_granite"), SET_WALL_GRANITE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_polished_granite"), SET_WALL_POLISHED_GRANITE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_diorite"), SET_WALL_DIORITE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_polished_diorite"), SET_WALL_POLISHED_DIORITE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_andesite"), SET_WALL_ANDESITE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_polished_andesite"), SET_WALL_POLISHED_ANDESITE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dirt"), SET_WALL_DIRT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_coarse_dirt"), SET_WALL_COARSE_DIRT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_crimson_nylium"), SET_WALL_CRIMSON_NYLIUM);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_warped_nylium"), SET_WALL_WARPED_NYLIUM);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cobblestone"), SET_WALL_COBBLESTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_oak_planks"), SET_WALL_OAK_PLANKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_spruce_planks"), SET_WALL_SPRUCE_PLANKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_birch_planks"), SET_WALL_BIRCH_PLANKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_jungle_planks"), SET_WALL_JUNGLE_PLANKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_acacia_planks"), SET_WALL_ACACIA_PLANKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dark_oak_planks"), SET_WALL_DARK_OAK_PLANKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_crimson_planks"), SET_WALL_CRIMSON_PLANKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_warped_planks"), SET_WALL_WARPED_PLANKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_bedrock"), SET_WALL_BEDROCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_sand"), SET_WALL_SAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_red_sand"), SET_WALL_RED_SAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_gravel"), SET_WALL_GRAVEL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_gold_ore"), SET_WALL_GOLD_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_iron_ore"), SET_WALL_IRON_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_coal_ore"), SET_WALL_COAL_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_nether_gold_ore"), SET_WALL_NETHER_GOLD_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_oak_log"), SET_WALL_OAK_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_spruce_log"), SET_WALL_SPRUCE_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_birch_log"), SET_WALL_BIRCH_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_jungle_log"), SET_WALL_JUNGLE_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_acacia_log"), SET_WALL_ACACIA_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dark_oak_log"), SET_WALL_DARK_OAK_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_crimson_stem"), SET_WALL_CRIMSON_STEM);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_warped_stem"), SET_WALL_WARPED_STEM);		
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stripped_oak_log"), SET_WALL_STRIPPED_OAK_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stripped_spruce_log"), SET_WALL_STRIPPED_SPRUCE_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stripped_birch_log"), SET_WALL_STRIPPED_BIRCH_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stripped_jungle_log"), SET_WALL_STRIPPED_JUNGLE_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stripped_acacia_log"), SET_WALL_STRIPPED_ACACIA_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stripped_dark_oak_log"), SET_WALL_STRIPPED_DARK_OAK_LOG);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stripped_crimson_stem"), SET_WALL_STRIPPED_CRIMSON_STEM);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stripped_warped_stem"), SET_WALL_STRIPPED_WARPED_STEM);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_sponge"), SET_WALL_SPONGE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_wet_sponge"), SET_WALL_WET_SPONGE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_lapis_ore"), SET_WALL_LAPIS_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_lapis_block"), SET_WALL_LAPIS_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dispenser"), SET_WALL_DISPENSER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_sandstone"), SET_WALL_SANDSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_chiseled_sandstone"), SET_WALL_CHISELED_SANDSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cut_sandstone"), SET_WALL_CUT_SANDSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_note_block"), SET_WALL_NOTE_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_white_wool"), SET_WALL_WHITE_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_orange_wool"), SET_WALL_ORANGE_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_magenta_wool"), SET_WALL_MAGENTA_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_blue_wool"), SET_WALL_LIGHT_BLUE_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_yellow_wool"), SET_WALL_YELLOW_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_lime_wool"), SET_WALL_LIME_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_pink_wool"), SET_WALL_PINK_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_gray_wool"), SET_WALL_GRAY_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_gray_wool"), SET_WALL_LIGHT_GRAY_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cyan_wool"), SET_WALL_CYAN_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_purple_wool"), SET_WALL_PURPLE_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_blue_wool"), SET_WALL_BLUE_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_brown_wool"), SET_WALL_BROWN_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_green_wool"), SET_WALL_GREEN_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_red_wool"), SET_WALL_RED_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_black_wool"), SET_WALL_BLACK_WOOL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_gold_block"), SET_WALL_GOLD_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_iron_block"), SET_WALL_IRON_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_smooth_quartz"), SET_WALL_SMOOTH_QUARTZ);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_smooth_red_sandstone"), SET_WALL_SMOOTH_RED_SANDSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_smooth_sandstone"), SET_WALL_SMOOTH_SANDSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_smooth_stone"), SET_WALL_SMOOTH_STONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_bricks"), SET_WALL_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_tnt"), SET_WALL_TNT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_bookshelf"), SET_WALL_BOOKSHELF);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_mossy_cobblestone"), SET_WALL_MOSSY_COBBLESTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_obsidian"), SET_WALL_OBSIDIAN);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_purpur_block"), SET_WALL_PURPUR_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_purpur_pillar"), SET_WALL_PURPUR_PILLAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_diamond_ore"), SET_WALL_DIAMOND_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_diamond_block"), SET_WALL_DIAMOND_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_redstone_ore"), SET_WALL_REDSTONE_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_ice"), SET_WALL_ICE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_snow_block"), SET_WALL_SNOW_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_clay"), SET_WALL_CLAY);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_jukebox"), SET_WALL_JUKEBOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_pumpkin"), SET_WALL_PUMPKIN);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_carved_pumpkin"), SET_WALL_CARVED_PUMPKIN);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_soul_sand"), SET_WALL_SOUL_SAND);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_soul_soil"), SET_WALL_SOUL_SOIL);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_basalt"), SET_WALL_BASALT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_basalt_top"), SET_WALL_BASALT_TOP);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_polished_basalt"), SET_WALL_POLISHED_BASALT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_polished_basalt_top"), SET_WALL_POLISHED_BASALT_TOP);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_glowstone"), SET_WALL_GLOWSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_stone_bricks"), SET_WALL_STONE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_mossy_stone_bricks"), SET_WALL_MOSSY_STONE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cracked_stone_bricks"), SET_WALL_CRACKED_STONE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_chiseled_stone_bricks"), SET_WALL_CHISELED_STONE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_brown_mushroom_block"), SET_WALL_BROWN_MUSHROOM_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_red_mushroom_block"), SET_WALL_RED_MUSHROOM_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_mushroom_inside"), SET_WALL_MUSHROOM_INSIDE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_mushroom_stem"), SET_WALL_MUSHROOM_STEM);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_melon"), SET_WALL_MELON);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_melon_top"), SET_WALL_MELON_TOP);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_nether_bricks"), SET_WALL_NETHER_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cracked_nether_bricks"), SET_WALL_CRACKED_NETHER_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_chiseled_nether_bricks"), SET_WALL_CHISELED_NETHER_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_end_stone"), SET_WALL_END_STONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_end_stone_bricks"), SET_WALL_END_STONE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_emerald_ore"), SET_WALL_EMERALD_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_emerald_block"), SET_WALL_EMERALD_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_redstone_block"), SET_WALL_REDSTONE_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_nether_quartz_ore"), SET_WALL_NETHER_QUARTZ_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_chiseled_quartz_block"), SET_WALL_CHISELED_QUARTZ_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_quartz_block"), SET_WALL_QUARTZ_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_quartz_bricks"), SET_WALL_QUARTZ_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_quartz_pillar"), SET_WALL_QUARTZ_PILLAR);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_white_terracotta"), SET_WALL_WHITE_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_orange_terracotta"), SET_WALL_ORANGE_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_magenta_terracotta"), SET_WALL_MAGENTA_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_blue_terracotta"), SET_WALL_LIGHT_BLUE_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_yellow_terracotta"), SET_WALL_YELLOW_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_lime_terracotta"), SET_WALL_LIME_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_pink_terracotta"), SET_WALL_PINK_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_gray_terracotta"), SET_WALL_GRAY_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_gray_terracotta"), SET_WALL_LIGHT_GRAY_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cyan_terracotta"), SET_WALL_CYAN_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_purple_terracotta"), SET_WALL_PURPLE_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_blue_terracotta"), SET_WALL_BLUE_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_brown_terracotta"), SET_WALL_BROWN_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_green_terracotta"), SET_WALL_GREEN_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_red_terracotta"), SET_WALL_RED_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_black_terracotta"), SET_WALL_BLACK_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_hay_block"), SET_WALL_HAY_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_hay_block_top"), SET_WALL_HAY_BLOCK_TOP);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_terracotta"), SET_WALL_TERRACOTTA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_coal_block"), SET_WALL_COAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_packed_ice"), SET_WALL_PACKED_ICE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_prismarine"), SET_WALL_PRISMARINE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_prismarine_bricks"), SET_WALL_PRISMARINE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dark_prismarine"), SET_WALL_DARK_PRISMARINE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_sea_lantern"), SET_WALL_SEA_LANTERN);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_red_sandstone"), SET_WALL_RED_SANDSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_chiseled_red_sandstone"), SET_WALL_CHISELED_RED_SANDSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cut_red_sandstone"), SET_WALL_CUT_RED_SANDSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_magma_block"), SET_WALL_MAGMA_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_nether_wart_block"), SET_WALL_NETHER_WART_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_warped_wart_block"), SET_WALL_WARPED_WART_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_red_nether_bricks"), SET_WALL_RED_NETHER_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_bone_block"), SET_WALL_BONE_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_observer"), SET_WALL_OBSERVER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_white_concrete"), SET_WALL_WHITE_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_orange_concrete"), SET_WALL_ORANGE_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_magenta_concrete"), SET_WALL_MAGENTA_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_blue_concrete"), SET_WALL_LIGHT_BLUE_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_yellow_concrete"), SET_WALL_YELLOW_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_lime_concrete"), SET_WALL_LIME_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_pink_concrete"), SET_WALL_PINK_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_gray_concrete"), SET_WALL_GRAY_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_gray_concrete"), SET_WALL_LIGHT_GRAY_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cyan_concrete"), SET_WALL_CYAN_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_purple_concrete"), SET_WALL_PURPLE_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_blue_concrete"), SET_WALL_BLUE_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_brown_concrete"), SET_WALL_BROWN_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_green_concrete"), SET_WALL_GREEN_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_red_concrete"), SET_WALL_RED_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_black_concrete"), SET_WALL_BLACK_CONCRETE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_white_concrete_powder"), SET_WALL_WHITE_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_orange_concrete_powder"), SET_WALL_ORANGE_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_magenta_concrete_powder"), SET_WALL_MAGENTA_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_blue_concrete_powder"), SET_WALL_LIGHT_BLUE_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_yellow_concrete_powder"), SET_WALL_YELLOW_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_lime_concrete_powder"), SET_WALL_LIME_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_pink_concrete_powder"), SET_WALL_PINK_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_gray_concrete_powder"), SET_WALL_GRAY_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_gray_concrete_powder"), SET_WALL_LIGHT_GRAY_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cyan_concrete_powder"), SET_WALL_CYAN_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_purple_concrete_powder"), SET_WALL_PURPLE_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_blue_concrete_powder"), SET_WALL_BLUE_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_brown_concrete_powder"), SET_WALL_BROWN_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_green_concrete_powder"), SET_WALL_GREEN_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_red_concrete_powder"), SET_WALL_RED_CONCRETE_POWDER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_black_concrete_powder"), SET_WALL_BLACK_CONCRETE_POWDER);	
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dead_tube_coral_block"), SET_WALL_DEAD_TUBE_CORAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dead_brain_coral_block"), SET_WALL_DEAD_BRAIN_CORAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dead_bubble_coral_block"), SET_WALL_DEAD_BUBBLE_CORAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dead_fire_coral_block"), SET_WALL_DEAD_FIRE_CORAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dead_horn_coral_block"), SET_WALL_DEAD_HORN_CORAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_tube_coral_block"), SET_WALL_TUBE_CORAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_brain_coral_block"), SET_WALL_BRAIN_CORAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_bubble_coral_block"), SET_WALL_BUBBLE_CORAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_fire_coral_block"), SET_WALL_FIRE_CORAL_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_horn_coral_block"), SET_WALL_HORN_CORAL_BLOCK);		
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_blue_ice"), SET_WALL_BLUE_ICE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dried_kelp_block"), SET_WALL_DRIED_KELP_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_composter"), SET_WALL_COMPOSTER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_smithing_table_top"), SET_WALL_SMITHING_TABLE_TOP);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_smithing_table_bottom"), SET_WALL_SMITHING_TABLE_BOTTOM);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_shroomlight"), SET_WALL_SHROOMLIGHT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_bee_nest"), SET_WALL_BEE_NEST);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_beehive"), SET_WALL_BEEHIVE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_honeycomb_block"), SET_WALL_HONEYCOMB_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_lodestone"), SET_WALL_LODESTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_lodestone_top"), SET_WALL_LODESTONE_TOP);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_netherite_block"), SET_WALL_NETHERITE_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_ancient_debris"), SET_WALL_ANCIENT_DEBRIS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_target"), SET_WALL_TARGET);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_crying_obsidian"), SET_WALL_CRYING_OBSIDIAN);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_netherrack"), SET_WALL_NETHERRACK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_blackstone"), SET_WALL_BLACKSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_polished_blackstone_bricks"), SET_WALL_POLISHED_BLACKSTONE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_gilded_blackstone"), SET_WALL_GILDED_BLACKSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_polished_blackstone"), SET_WALL_POLISHED_BLACKSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_chiseled_polished_blackstone"), SET_WALL_CHISELED_POLISHED_BLACKSTONE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cracked_polished_blackstone_bricks"), SET_WALL_CRACKED_POLISHED_BLACKSTONE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_gold_ore"), SET_WALL_DEEPSLATE_GOLD_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_iron_ore"), SET_WALL_DEEPSLATE_IRON_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_coal_ore"), SET_WALL_DEEPSLATE_COAL_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_lapis_ore"), SET_WALL_DEEPSLATE_LAPIS_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_diamond_ore"), SET_WALL_DEEPSLATE_DIAMOND_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_redstone_ore"), SET_WALL_DEEPSLATE_REDSTONE_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_emerald_ore"), SET_WALL_DEEPSLATE_EMERALD_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_copper_ore"), SET_WALL_DEEPSLATE_COPPER_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_azalea"), SET_WALL_AZALEA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_flowering_azalea"), SET_WALL_FLOWERING_AZALEA);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_moss_block"), SET_WALL_MOSS_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_rooted_dirt"), SET_WALL_ROOTED_DIRT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_shulker_box"), SET_WALL_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_white_shulker_box"), SET_WALL_WHITE_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_orange_shulker_box"), SET_WALL_ORANGE_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_magenta_shulker_box"), SET_WALL_MAGENTA_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_blue_shulker_box"), SET_WALL_LIGHT_BLUE_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_yellow_shulker_box"), SET_WALL_YELLOW_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_lime_shulker_box"), SET_WALL_LIME_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_pink_shulker_box"), SET_WALL_PINK_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_gray_shulker_box"), SET_WALL_GRAY_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_light_gray_shulker_box"), SET_WALL_LIGHT_GRAY_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cyan_shulker_box"), SET_WALL_CYAN_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_purple_shulker_box"), SET_WALL_PURPLE_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_blue_shulker_box"), SET_WALL_BLUE_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_brown_shulker_box"), SET_WALL_BROWN_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_green_shulker_box"), SET_WALL_GREEN_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_red_shulker_box"), SET_WALL_RED_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_black_shulker_box"), SET_WALL_BLACK_SHULKER_BOX);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_amethyst_block"), SET_WALL_AMETHYST_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_budding_amethyst"), SET_WALL_BUDDING_AMETHYST);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_tuff"), SET_WALL_TUFF);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_calcite"), SET_WALL_CALCITE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_powder_snow"), SET_WALL_POWDER_SNOW);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_oxidized_copper"), SET_WALL_OXIDIZED_COPPER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_weathered_copper"), SET_WALL_WEATHERED_COPPER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_exposed_copper"), SET_WALL_EXPOSED_COPPER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_copper_block"), SET_WALL_COPPER_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_copper_ore"), SET_WALL_COPPER_ORE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_oxidized_cut_copper"), SET_WALL_OXIDIZED_CUT_COPPER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_weathered_cut_copper"), SET_WALL_WEATHERED_CUT_COPPER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_exposed_cut_copper"), SET_WALL_EXPOSED_CUT_COPPER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cut_copper"), SET_WALL_CUT_COPPER);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_dripstone_block"), SET_WALL_DRIPSTONE_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate"), SET_WALL_DEEPSLATE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cobbled_deepslate"), SET_WALL_COBBLED_DEEPSLATE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_polished_deepslate"), SET_WALL_POLISHED_DEEPSLATE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_tiles"), SET_WALL_DEEPSLATE_TILES);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_deepslate_bricks"), SET_WALL_DEEPSLATE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_chiseled_deepslate"), SET_WALL_CHISELED_DEEPSLATE);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cracked_deepslate_bricks"), SET_WALL_CRACKED_DEEPSLATE_BRICKS);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_cracked_deepslate_tiles"), SET_WALL_CRACKED_DEEPSLATE_TILES);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_smooth_basalt"), SET_WALL_SMOOTH_BASALT);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_raw_iron_block"), SET_WALL_RAW_IRON_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_raw_copper_block"), SET_WALL_RAW_COPPER_BLOCK);
		Registry.register(Registry.BLOCK, new Identifier("tvstudio", "set_wall_raw_gold_block"), SET_WALL_RAW_GOLD_BLOCK);
		
	}
}
