package io.github.joppebijlsma.tvstudio.registries;

import io.github.joppebijlsma.tvstudio.TvStudio;
import io.github.joppebijlsma.tvstudio.items.DyeableModArmorItem;
import io.github.joppebijlsma.tvstudio.items.ModArmorMaterial;
import io.github.joppebijlsma.tvstudio.items.WashingTowel;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class ModItems {

	public static final Item LENS = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item CLAPBOARD = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item BOOMPOLE_MICROPHONE = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));	
	public static final Item WASHING_TOWEL = new WashingTowel(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item GREEN_NEON_ORB = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item GREEN_SCREEN_DYE = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item BLUE_NEON_ORB = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item BLUE_SCREEN_DYE = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item IRON_STICK = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item POLE = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item TV_STAND_HEAD = new Item(new FabricItemSettings().group(TvStudio.ITEMS_GROUP));
	public static final Item HEADSET = new DyeableModArmorItem(ModArmorMaterial.HEADSER_MATERIAL, EquipmentSlot.HEAD, new Item.Settings().group(TvStudio.ITEMS_GROUP));
	
	public static void register() {
		
		//ITEMS
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "lens"), LENS);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "clapboard"), CLAPBOARD);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "boompole_microphone"), BOOMPOLE_MICROPHONE);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "washing_towel"), WASHING_TOWEL);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "green_neon_orb"), GREEN_NEON_ORB);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "green_screen_dye"), GREEN_SCREEN_DYE);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "blue_neon_orb"), BLUE_NEON_ORB);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "blue_screen_dye"), BLUE_SCREEN_DYE);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "iron_stick"), IRON_STICK);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "pole"), POLE);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "tv_stand_head"), TV_STAND_HEAD);
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "headset"), HEADSET);
		
		//BlockItems
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "tv_camera"), new BlockItem(ModBlocks.TV_CAMERA, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "chipboard_block"), new BlockItem(ModBlocks.CHIPBOARD_BLOCK, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_support"), new BlockItem(ModBlocks.SET_WALL_SUPPORT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));	
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "blue_screen_block"), new BlockItem(ModBlocks.BLUE_SCREEN_BLOCK, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "blue_screen_wall"), new BlockItem(ModBlocks.BLUE_SCREEN_WALL, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "green_screen_block"), new BlockItem(ModBlocks.GREEN_SCREEN_BLOCK, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "green_screen_wall"), new BlockItem(ModBlocks.GREEN_SCREEN_WALL, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));		
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "white_tv_stand"), new BlockItem(ModBlocks.WHITE_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "orange_tv_stand"), new BlockItem(ModBlocks.ORANGE_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "magenta_tv_stand"), new BlockItem(ModBlocks.MAGENTA_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_blue_tv_stand"), new BlockItem(ModBlocks.LIGHT_BLUE_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "yellow_tv_stand"), new BlockItem(ModBlocks.YELLOW_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "lime_tv_stand"), new BlockItem(ModBlocks.LIME_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "pink_tv_stand"), new BlockItem(ModBlocks.PINK_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "gray_tv_stand"), new BlockItem(ModBlocks.GRAY_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_gray_tv_stand"), new BlockItem(ModBlocks.LIGHT_GRAY_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "cyan_tv_stand"), new BlockItem(ModBlocks.CYAN_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "purple_tv_stand"), new BlockItem(ModBlocks.PURPLE_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "blue_tv_stand"), new BlockItem(ModBlocks.BLUE_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "brown_tv_stand"), new BlockItem(ModBlocks.BROWN_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "green_tv_stand"), new BlockItem(ModBlocks.GREEN_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "red_tv_stand"), new BlockItem(ModBlocks.RED_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "black_tv_stand"), new BlockItem(ModBlocks.BLACK_TV_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));		
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "white_tv_camera_on_stand"), new BlockItem(ModBlocks.WHITE_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "orange_tv_camera_on_stand"), new BlockItem(ModBlocks.ORANGE_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "magenta_tv_camera_on_stand"), new BlockItem(ModBlocks.MAGENTA_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_blue_tv_camera_on_stand"), new BlockItem(ModBlocks.LIGHT_BLUE_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "yellow_tv_camera_on_stand"), new BlockItem(ModBlocks.YELLOW_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "lime_tv_camera_on_stand"), new BlockItem(ModBlocks.LIME_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "pink_tv_camera_on_stand"), new BlockItem(ModBlocks.PINK_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "gray_tv_camera_on_stand"), new BlockItem(ModBlocks.GRAY_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_gray_tv_camera_on_stand"), new BlockItem(ModBlocks.LIGHT_GRAY_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "cyan_tv_camera_on_stand"), new BlockItem(ModBlocks.CYAN_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "purple_tv_camera_on_stand"), new BlockItem(ModBlocks.PURPLE_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "blue_tv_camera_on_stand"), new BlockItem(ModBlocks.BLUE_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "brown_tv_camera_on_stand"), new BlockItem(ModBlocks.BROWN_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "green_tv_camera_on_stand"), new BlockItem(ModBlocks.GREEN_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "red_tv_camera_on_stand"), new BlockItem(ModBlocks.RED_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "black_tv_camera_on_stand"), new BlockItem(ModBlocks.BLACK_TV_CAMERA_ON_STAND, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));		
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "white_studio_light"), new BlockItem(ModBlocks.WHITE_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "orange_studio_light"), new BlockItem(ModBlocks.ORANGE_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "magenta_studio_light"), new BlockItem(ModBlocks.MAGENTA_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_blue_studio_light"), new BlockItem(ModBlocks.LIGHT_BLUE_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "yellow_studio_light"), new BlockItem(ModBlocks.YELLOW_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "lime_studio_light"), new BlockItem(ModBlocks.LIME_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "pink_studio_light"), new BlockItem(ModBlocks.PINK_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "gray_studio_light"), new BlockItem(ModBlocks.GRAY_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_gray_studio_light"), new BlockItem(ModBlocks.LIGHT_GRAY_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "cyan_studio_light"), new BlockItem(ModBlocks.CYAN_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "purple_studio_light"), new BlockItem(ModBlocks.PURPLE_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "blue_studio_light"), new BlockItem(ModBlocks.BLUE_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "brown_studio_light"), new BlockItem(ModBlocks.BROWN_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "green_studio_light"), new BlockItem(ModBlocks.GREEN_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "red_studio_light"), new BlockItem(ModBlocks.RED_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "black_studio_light"), new BlockItem(ModBlocks.BLACK_STUDIO_LIGHT, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));		
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "white_studio_bar"), new BlockItem(ModBlocks.WHITE_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "orange_studio_bar"), new BlockItem(ModBlocks.ORANGE_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "magenta_studio_bar"), new BlockItem(ModBlocks.MAGENTA_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_blue_studio_bar"), new BlockItem(ModBlocks.LIGHT_BLUE_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "yellow_studio_bar"), new BlockItem(ModBlocks.YELLOW_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "lime_studio_bar"), new BlockItem(ModBlocks.LIME_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "pink_studio_bar"), new BlockItem(ModBlocks.PINK_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "gray_studio_bar"), new BlockItem(ModBlocks.GRAY_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_gray_studio_bar"), new BlockItem(ModBlocks.LIGHT_GRAY_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "cyan_studio_bar"), new BlockItem(ModBlocks.CYAN_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "purple_studio_bar"), new BlockItem(ModBlocks.PURPLE_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "blue_studio_bar"), new BlockItem(ModBlocks.BLUE_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "brown_studio_bar"), new BlockItem(ModBlocks.BROWN_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "green_studio_bar"), new BlockItem(ModBlocks.GREEN_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "red_studio_bar"), new BlockItem(ModBlocks.RED_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "black_studio_bar"), new BlockItem(ModBlocks.BLACK_STUDIO_BAR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));		
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "white_director_chair"), new BlockItem(ModBlocks.WHITE_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "orange_director_chair"), new BlockItem(ModBlocks.ORANGE_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "magenta_director_chair"), new BlockItem(ModBlocks.MAGENTA_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_blue_director_chair"), new BlockItem(ModBlocks.LIGHT_BLUE_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "yellow_director_chair"), new BlockItem(ModBlocks.YELLOW_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "lime_director_chair"), new BlockItem(ModBlocks.LIME_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "pink_director_chair"), new BlockItem(ModBlocks.PINK_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "gray_director_chair"), new BlockItem(ModBlocks.GRAY_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "light_gray_director_chair"), new BlockItem(ModBlocks.LIGHT_GRAY_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "cyan_director_chair"), new BlockItem(ModBlocks.CYAN_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "purple_director_chair"), new BlockItem(ModBlocks.PURPLE_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "blue_director_chair"), new BlockItem(ModBlocks.BLUE_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "brown_director_chair"), new BlockItem(ModBlocks.BROWN_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "green_director_chair"), new BlockItem(ModBlocks.GREEN_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "red_director_chair"), new BlockItem(ModBlocks.RED_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "black_director_chair"), new BlockItem(ModBlocks.BLACK_DIRECTOR_CHAIR, new FabricItemSettings().group(TvStudio.BLOCKS_GROUP)));			
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall"), new BlockItem(ModBlocks.SET_WALL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stone"), new BlockItem(ModBlocks.SET_WALL_STONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_granite"), new BlockItem(ModBlocks.SET_WALL_GRANITE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_polished_granite"), new BlockItem(ModBlocks.SET_WALL_POLISHED_GRANITE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_diorite"), new BlockItem(ModBlocks.SET_WALL_DIORITE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_polished_diorite"), new BlockItem(ModBlocks.SET_WALL_POLISHED_DIORITE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_andesite"), new BlockItem(ModBlocks.SET_WALL_ANDESITE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_polished_andesite"), new BlockItem(ModBlocks.SET_WALL_POLISHED_ANDESITE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dirt"), new BlockItem(ModBlocks.SET_WALL_DIRT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_crimson_nylium"), new BlockItem(ModBlocks.SET_WALL_CRIMSON_NYLIUM, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_warped_nylium"), new BlockItem(ModBlocks.SET_WALL_WARPED_NYLIUM, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cobblestone"), new BlockItem(ModBlocks.SET_WALL_COBBLESTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_oak_planks"), new BlockItem(ModBlocks.SET_WALL_OAK_PLANKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_spruce_planks"), new BlockItem(ModBlocks.SET_WALL_SPRUCE_PLANKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_birch_planks"), new BlockItem(ModBlocks.SET_WALL_BIRCH_PLANKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_jungle_planks"), new BlockItem(ModBlocks.SET_WALL_JUNGLE_PLANKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_acacia_planks"), new BlockItem(ModBlocks.SET_WALL_ACACIA_PLANKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dark_oak_planks"), new BlockItem(ModBlocks.SET_WALL_DARK_OAK_PLANKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_crimson_planks"), new BlockItem(ModBlocks.SET_WALL_CRIMSON_PLANKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_warped_planks"), new BlockItem(ModBlocks.SET_WALL_WARPED_PLANKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_bedrock"), new BlockItem(ModBlocks.SET_WALL_BEDROCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_sand"), new BlockItem(ModBlocks.SET_WALL_SAND, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_red_sand"), new BlockItem(ModBlocks.SET_WALL_RED_SAND, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_gravel"), new BlockItem(ModBlocks.SET_WALL_GRAVEL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_gold_ore"), new BlockItem(ModBlocks.SET_WALL_GOLD_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_iron_ore"), new BlockItem(ModBlocks.SET_WALL_IRON_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_coal_ore"), new BlockItem(ModBlocks.SET_WALL_COAL_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_nether_gold_ore"), new BlockItem(ModBlocks.SET_WALL_NETHER_GOLD_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_oak_log"), new BlockItem(ModBlocks.SET_WALL_OAK_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_spruce_log"), new BlockItem(ModBlocks.SET_WALL_SPRUCE_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_birch_log"), new BlockItem(ModBlocks.SET_WALL_BIRCH_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_jungle_log"), new BlockItem(ModBlocks.SET_WALL_JUNGLE_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_acacia_log"), new BlockItem(ModBlocks.SET_WALL_ACACIA_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dark_oak_log"), new BlockItem(ModBlocks.SET_WALL_DARK_OAK_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_crimson_stem"), new BlockItem(ModBlocks.SET_WALL_CRIMSON_STEM, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_warped_stem"), new BlockItem(ModBlocks.SET_WALL_WARPED_STEM, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stripped_oak_log"), new BlockItem(ModBlocks.SET_WALL_STRIPPED_OAK_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stripped_spruce_log"), new BlockItem(ModBlocks.SET_WALL_STRIPPED_SPRUCE_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stripped_birch_log"), new BlockItem(ModBlocks.SET_WALL_STRIPPED_BIRCH_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stripped_jungle_log"), new BlockItem(ModBlocks.SET_WALL_STRIPPED_JUNGLE_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stripped_acacia_log"), new BlockItem(ModBlocks.SET_WALL_STRIPPED_ACACIA_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stripped_dark_oak_log"), new BlockItem(ModBlocks.SET_WALL_STRIPPED_DARK_OAK_LOG, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stripped_crimson_stem"), new BlockItem(ModBlocks.SET_WALL_STRIPPED_CRIMSON_STEM, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stripped_warped_stem"), new BlockItem(ModBlocks.SET_WALL_STRIPPED_WARPED_STEM, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));	
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_sponge"), new BlockItem(ModBlocks.SET_WALL_SPONGE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_wet_sponge"), new BlockItem(ModBlocks.SET_WALL_WET_SPONGE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_lapis_ore"), new BlockItem(ModBlocks.SET_WALL_LAPIS_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_lapis_block"), new BlockItem(ModBlocks.SET_WALL_LAPIS_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dispenser"), new BlockItem(ModBlocks.SET_WALL_DISPENSER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_sandstone"), new BlockItem(ModBlocks.SET_WALL_SANDSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_chiseled_sandstone"), new BlockItem(ModBlocks.SET_WALL_CHISELED_SANDSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cut_sandstone"), new BlockItem(ModBlocks.SET_WALL_CUT_SANDSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_note_block"), new BlockItem(ModBlocks.SET_WALL_NOTE_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_white_wool"), new BlockItem(ModBlocks.SET_WALL_WHITE_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_orange_wool"), new BlockItem(ModBlocks.SET_WALL_ORANGE_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_magenta_wool"), new BlockItem(ModBlocks.SET_WALL_MAGENTA_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_blue_wool"), new BlockItem(ModBlocks.SET_WALL_LIGHT_BLUE_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_yellow_wool"), new BlockItem(ModBlocks.SET_WALL_YELLOW_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_lime_wool"), new BlockItem(ModBlocks.SET_WALL_LIME_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_pink_wool"), new BlockItem(ModBlocks.SET_WALL_PINK_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_gray_wool"), new BlockItem(ModBlocks.SET_WALL_GRAY_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_gray_wool"), new BlockItem(ModBlocks.SET_WALL_LIGHT_GRAY_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cyan_wool"), new BlockItem(ModBlocks.SET_WALL_CYAN_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_purple_wool"), new BlockItem(ModBlocks.SET_WALL_PURPLE_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_blue_wool"), new BlockItem(ModBlocks.SET_WALL_BLUE_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_brown_wool"), new BlockItem(ModBlocks.SET_WALL_BROWN_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_green_wool"), new BlockItem(ModBlocks.SET_WALL_GREEN_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_red_wool"), new BlockItem(ModBlocks.SET_WALL_RED_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_black_wool"), new BlockItem(ModBlocks.SET_WALL_BLACK_WOOL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));	
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_gold_block"), new BlockItem(ModBlocks.SET_WALL_GOLD_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_iron_block"), new BlockItem(ModBlocks.SET_WALL_IRON_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_smooth_quartz"), new BlockItem(ModBlocks.SET_WALL_SMOOTH_QUARTZ, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_smooth_red_sandstone"), new BlockItem(ModBlocks.SET_WALL_SMOOTH_RED_SANDSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_smooth_sandstone"), new BlockItem(ModBlocks.SET_WALL_SMOOTH_SANDSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_smooth_stone"), new BlockItem(ModBlocks.SET_WALL_SMOOTH_STONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_bricks"), new BlockItem(ModBlocks.SET_WALL_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_tnt"), new BlockItem(ModBlocks.SET_WALL_TNT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_bookshelf"), new BlockItem(ModBlocks.SET_WALL_BOOKSHELF, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_mossy_cobblestone"), new BlockItem(ModBlocks.SET_WALL_MOSSY_COBBLESTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_obsidian"), new BlockItem(ModBlocks.SET_WALL_OBSIDIAN, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_purpur_block"), new BlockItem(ModBlocks.SET_WALL_PURPUR_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_purpur_pillar"), new BlockItem(ModBlocks.SET_WALL_PURPUR_PILLAR, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_diamond_ore"), new BlockItem(ModBlocks.SET_WALL_DIAMOND_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_diamond_block"), new BlockItem(ModBlocks.SET_WALL_DIAMOND_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_redstone_ore"), new BlockItem(ModBlocks.SET_WALL_REDSTONE_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_ice"), new BlockItem(ModBlocks.SET_WALL_ICE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_snow_block"), new BlockItem(ModBlocks.SET_WALL_SNOW_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_clay"), new BlockItem(ModBlocks.SET_WALL_CLAY, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_jukebox"), new BlockItem(ModBlocks.SET_WALL_JUKEBOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_pumpkin"), new BlockItem(ModBlocks.SET_WALL_PUMPKIN, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_carved_pumpkin"), new BlockItem(ModBlocks.SET_WALL_CARVED_PUMPKIN, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_soul_sand"), new BlockItem(ModBlocks.SET_WALL_SOUL_SAND, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_soul_soil"), new BlockItem(ModBlocks.SET_WALL_SOUL_SOIL, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_basalt"), new BlockItem(ModBlocks.SET_WALL_BASALT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_basalt_top"), new BlockItem(ModBlocks.SET_WALL_BASALT_TOP, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_polished_basalt"), new BlockItem(ModBlocks.SET_WALL_POLISHED_BASALT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_polished_basalt_top"), new BlockItem(ModBlocks.SET_WALL_POLISHED_BASALT_TOP, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_glowstone"), new BlockItem(ModBlocks.SET_WALL_GLOWSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stone_bricks"), new BlockItem(ModBlocks.SET_WALL_STONE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_mossy_stone_bricks"), new BlockItem(ModBlocks.SET_WALL_MOSSY_STONE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cracked_stone_bricks"), new BlockItem(ModBlocks.SET_WALL_CRACKED_STONE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_chiseled_stone_bricks"), new BlockItem(ModBlocks.SET_WALL_CHISELED_STONE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_brown_mushroom_block"), new BlockItem(ModBlocks.SET_WALL_BROWN_MUSHROOM_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_red_mushroom_block"), new BlockItem(ModBlocks.SET_WALL_RED_MUSHROOM_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_mushroom_inside"), new BlockItem(ModBlocks.SET_WALL_MUSHROOM_INSIDE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_mushroom_stem"), new BlockItem(ModBlocks.SET_WALL_MUSHROOM_STEM, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_melon"), new BlockItem(ModBlocks.SET_WALL_MELON, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_melon_top"), new BlockItem(ModBlocks.SET_WALL_MELON_TOP, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_nether_bricks"), new BlockItem(ModBlocks.SET_WALL_NETHER_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cracked_nether_bricks"), new BlockItem(ModBlocks.SET_WALL_CRACKED_NETHER_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_chiseled_nether_bricks"), new BlockItem(ModBlocks.SET_WALL_CHISELED_NETHER_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_end_stone"), new BlockItem(ModBlocks.SET_WALL_END_STONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_end_stone_bricks"), new BlockItem(ModBlocks.SET_WALL_END_STONE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_emerald_ore"), new BlockItem(ModBlocks.SET_WALL_EMERALD_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_emerald_block"), new BlockItem(ModBlocks.SET_WALL_EMERALD_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_redstone_block"), new BlockItem(ModBlocks.SET_WALL_REDSTONE_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_nether_quartz_ore"), new BlockItem(ModBlocks.SET_WALL_NETHER_QUARTZ_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_chiseled_quartz_block"), new BlockItem(ModBlocks.SET_WALL_CHISELED_QUARTZ_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_quartz_block"), new BlockItem(ModBlocks.SET_WALL_QUARTZ_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_quartz_bricks"), new BlockItem(ModBlocks.SET_WALL_QUARTZ_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_quartz_pillar"), new BlockItem(ModBlocks.SET_WALL_QUARTZ_PILLAR, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_white_terracotta"), new BlockItem(ModBlocks.SET_WALL_WHITE_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_orange_terracotta"), new BlockItem(ModBlocks.SET_WALL_ORANGE_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_magenta_terracotta"), new BlockItem(ModBlocks.SET_WALL_MAGENTA_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_blue_terracotta"), new BlockItem(ModBlocks.SET_WALL_LIGHT_BLUE_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_yellow_terracotta"), new BlockItem(ModBlocks.SET_WALL_YELLOW_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_lime_terracotta"), new BlockItem(ModBlocks.SET_WALL_LIME_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_pink_terracotta"), new BlockItem(ModBlocks.SET_WALL_PINK_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_gray_terracotta"), new BlockItem(ModBlocks.SET_WALL_GRAY_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_gray_terracotta"), new BlockItem(ModBlocks.SET_WALL_LIGHT_GRAY_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cyan_terracotta"), new BlockItem(ModBlocks.SET_WALL_CYAN_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_purple_terracotta"), new BlockItem(ModBlocks.SET_WALL_PURPLE_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_blue_terracotta"), new BlockItem(ModBlocks.SET_WALL_BLUE_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_brown_terracotta"), new BlockItem(ModBlocks.SET_WALL_BROWN_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_green_terracotta"), new BlockItem(ModBlocks.SET_WALL_GREEN_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_red_terracotta"), new BlockItem(ModBlocks.SET_WALL_RED_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_black_terracotta"), new BlockItem(ModBlocks.SET_WALL_BLACK_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_hay_block"), new BlockItem(ModBlocks.SET_WALL_HAY_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_hay_block_top"), new BlockItem(ModBlocks.SET_WALL_HAY_BLOCK_TOP, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_terracotta"), new BlockItem(ModBlocks.SET_WALL_TERRACOTTA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_coal_block"), new BlockItem(ModBlocks.SET_WALL_COAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_packed_ice"), new BlockItem(ModBlocks.SET_WALL_PACKED_ICE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_prismarine"), new BlockItem(ModBlocks.SET_WALL_PRISMARINE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_prismarine_bricks"), new BlockItem(ModBlocks.SET_WALL_PRISMARINE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dark_prismarine"), new BlockItem(ModBlocks.SET_WALL_DARK_PRISMARINE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_sea_lantern"), new BlockItem(ModBlocks.SET_WALL_SEA_LANTERN, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_red_sandstone"), new BlockItem(ModBlocks.SET_WALL_RED_SANDSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_chiseled_red_sandstone"), new BlockItem(ModBlocks.SET_WALL_CHISELED_RED_SANDSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cut_red_sandstone"), new BlockItem(ModBlocks.SET_WALL_CUT_RED_SANDSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_magma_block"), new BlockItem(ModBlocks.SET_WALL_MAGMA_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_nether_wart_block"), new BlockItem(ModBlocks.SET_WALL_NETHER_WART_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_warped_wart_block"), new BlockItem(ModBlocks.SET_WALL_WARPED_WART_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_red_nether_bricks"), new BlockItem(ModBlocks.SET_WALL_RED_NETHER_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_bone_block"), new BlockItem(ModBlocks.SET_WALL_BONE_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_observer"), new BlockItem(ModBlocks.SET_WALL_OBSERVER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_white_concrete"), new BlockItem(ModBlocks.SET_WALL_WHITE_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_orange_concrete"), new BlockItem(ModBlocks.SET_WALL_ORANGE_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_magenta_concrete"), new BlockItem(ModBlocks.SET_WALL_MAGENTA_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_blue_concrete"), new BlockItem(ModBlocks.SET_WALL_LIGHT_BLUE_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_yellow_concrete"), new BlockItem(ModBlocks.SET_WALL_YELLOW_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_lime_concrete"), new BlockItem(ModBlocks.SET_WALL_LIME_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_pink_concrete"), new BlockItem(ModBlocks.SET_WALL_PINK_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_gray_concrete"), new BlockItem(ModBlocks.SET_WALL_GRAY_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_gray_concrete"), new BlockItem(ModBlocks.SET_WALL_LIGHT_GRAY_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cyan_concrete"), new BlockItem(ModBlocks.SET_WALL_CYAN_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_purple_concrete"), new BlockItem(ModBlocks.SET_WALL_PURPLE_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_blue_concrete"), new BlockItem(ModBlocks.SET_WALL_BLUE_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_brown_concrete"), new BlockItem(ModBlocks.SET_WALL_BROWN_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_green_concrete"), new BlockItem(ModBlocks.SET_WALL_GREEN_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_red_concrete"), new BlockItem(ModBlocks.SET_WALL_RED_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_black_concrete"), new BlockItem(ModBlocks.SET_WALL_BLACK_CONCRETE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_white_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_WHITE_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_orange_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_ORANGE_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_magenta_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_MAGENTA_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_blue_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_LIGHT_BLUE_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_yellow_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_YELLOW_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_lime_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_LIME_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_pink_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_PINK_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_gray_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_GRAY_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_gray_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_LIGHT_GRAY_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cyan_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_CYAN_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_purple_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_PURPLE_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_blue_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_BLUE_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_brown_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_BROWN_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_green_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_GREEN_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_red_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_RED_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_black_concrete_powder"), new BlockItem(ModBlocks.SET_WALL_BLACK_CONCRETE_POWDER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_tube_coral_block"), new BlockItem(ModBlocks.SET_WALL_TUBE_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_brain_coral_block"), new BlockItem(ModBlocks.SET_WALL_BRAIN_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_bubble_coral_block"), new BlockItem(ModBlocks.SET_WALL_BUBBLE_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_fire_coral_block"), new BlockItem(ModBlocks.SET_WALL_FIRE_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_horn_coral_block"), new BlockItem(ModBlocks.SET_WALL_HORN_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dead_tube_coral_block"), new BlockItem(ModBlocks.SET_WALL_DEAD_TUBE_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dead_brain_coral_block"), new BlockItem(ModBlocks.SET_WALL_DEAD_BRAIN_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dead_bubble_coral_block"), new BlockItem(ModBlocks.SET_WALL_DEAD_BUBBLE_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dead_fire_coral_block"), new BlockItem(ModBlocks.SET_WALL_DEAD_FIRE_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dead_horn_coral_block"), new BlockItem(ModBlocks.SET_WALL_DEAD_HORN_CORAL_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_blue_ice"), new BlockItem(ModBlocks.SET_WALL_BLUE_ICE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dried_kelp_block"), new BlockItem(ModBlocks.SET_WALL_DRIED_KELP_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_composter"), new BlockItem(ModBlocks.SET_WALL_COMPOSTER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_smithing_table_top"), new BlockItem(ModBlocks.SET_WALL_SMITHING_TABLE_TOP, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_smithing_table_bottom"), new BlockItem(ModBlocks.SET_WALL_SMITHING_TABLE_BOTTOM, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_shroomlight"), new BlockItem(ModBlocks.SET_WALL_SHROOMLIGHT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_bee_nest"), new BlockItem(ModBlocks.SET_WALL_BEE_NEST, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_beehive"), new BlockItem(ModBlocks.SET_WALL_BEEHIVE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_honeycomb_block"), new BlockItem(ModBlocks.SET_WALL_HONEYCOMB_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_lodestone"), new BlockItem(ModBlocks.SET_WALL_LODESTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_lodestone_top"), new BlockItem(ModBlocks.SET_WALL_LODESTONE_TOP, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_netherite_block"), new BlockItem(ModBlocks.SET_WALL_NETHERITE_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_ancient_debris"), new BlockItem(ModBlocks.SET_WALL_ANCIENT_DEBRIS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_target"), new BlockItem(ModBlocks.SET_WALL_TARGET, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_crying_obsidian"), new BlockItem(ModBlocks.SET_WALL_CRYING_OBSIDIAN, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_netherrack"), new BlockItem(ModBlocks.SET_WALL_NETHERRACK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_gilded_blackstone"), new BlockItem(ModBlocks.SET_WALL_GILDED_BLACKSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_blackstone"), new BlockItem(ModBlocks.SET_WALL_BLACKSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_polished_blackstone"), new BlockItem(ModBlocks.SET_WALL_POLISHED_BLACKSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_chiseled_polished_blackstone"), new BlockItem(ModBlocks.SET_WALL_CHISELED_POLISHED_BLACKSTONE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_polished_blackstone_bricks"), new BlockItem(ModBlocks.SET_WALL_POLISHED_BLACKSTONE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cracked_polished_blackstone_bricks"), new BlockItem(ModBlocks.SET_WALL_CRACKED_POLISHED_BLACKSTONE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));	
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_gold_ore"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_GOLD_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_iron_ore"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_IRON_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_coal_ore"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_COAL_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_lapis_ore"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_LAPIS_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_diamond_ore"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_DIAMOND_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_redstone_ore"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_REDSTONE_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_emerald_ore"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_EMERALD_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_copper_ore"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_COPPER_ORE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_azalea"), new BlockItem(ModBlocks.SET_WALL_AZALEA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_flowering_azalea"), new BlockItem(ModBlocks.SET_WALL_FLOWERING_AZALEA, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_moss_block"), new BlockItem(ModBlocks.SET_WALL_MOSS_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_rooted_dirt"), new BlockItem(ModBlocks.SET_WALL_ROOTED_DIRT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_shulker_box"), new BlockItem(ModBlocks.SET_WALL_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_white_shulker_box"), new BlockItem(ModBlocks.SET_WALL_WHITE_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_orange_shulker_box"), new BlockItem(ModBlocks.SET_WALL_ORANGE_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_magenta_shulker_box"), new BlockItem(ModBlocks.SET_WALL_MAGENTA_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_blue_shulker_box"), new BlockItem(ModBlocks.SET_WALL_LIGHT_BLUE_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_yellow_shulker_box"), new BlockItem(ModBlocks.SET_WALL_YELLOW_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_lime_shulker_box"), new BlockItem(ModBlocks.SET_WALL_LIME_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_pink_shulker_box"), new BlockItem(ModBlocks.SET_WALL_PINK_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_gray_shulker_box"), new BlockItem(ModBlocks.SET_WALL_GRAY_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_light_gray_shulker_box"), new BlockItem(ModBlocks.SET_WALL_LIGHT_GRAY_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cyan_shulker_box"), new BlockItem(ModBlocks.SET_WALL_CYAN_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_purple_shulker_box"), new BlockItem(ModBlocks.SET_WALL_PURPLE_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_blue_shulker_box"), new BlockItem(ModBlocks.SET_WALL_BLUE_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_brown_shulker_box"), new BlockItem(ModBlocks.SET_WALL_BROWN_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_green_shulker_box"), new BlockItem(ModBlocks.SET_WALL_GREEN_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_red_shulker_box"), new BlockItem(ModBlocks.SET_WALL_RED_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_black_shulker_box"), new BlockItem(ModBlocks.SET_WALL_BLACK_SHULKER_BOX, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_amethyst_block"), new BlockItem(ModBlocks.SET_WALL_AMETHYST_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_budding_amethyst"), new BlockItem(ModBlocks.SET_WALL_BUDDING_AMETHYST, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_tuff"), new BlockItem(ModBlocks.SET_WALL_TUFF, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_calcite"), new BlockItem(ModBlocks.SET_WALL_CALCITE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_powder_snow"), new BlockItem(ModBlocks.SET_WALL_POWDER_SNOW, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_oxidized_copper"), new BlockItem(ModBlocks.SET_WALL_OXIDIZED_COPPER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_weathered_copper"), new BlockItem(ModBlocks.SET_WALL_WEATHERED_COPPER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_exposed_copper"), new BlockItem(ModBlocks.SET_WALL_EXPOSED_COPPER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_copper_block"), new BlockItem(ModBlocks.SET_WALL_COPPER_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_oxidized_cut_copper"), new BlockItem(ModBlocks.SET_WALL_OXIDIZED_CUT_COPPER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_weathered_cut_copper"), new BlockItem(ModBlocks.SET_WALL_WEATHERED_CUT_COPPER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_exposed_cut_copper"), new BlockItem(ModBlocks.SET_WALL_EXPOSED_CUT_COPPER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cut_copper"), new BlockItem(ModBlocks.SET_WALL_CUT_COPPER, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_dripstone_block"), new BlockItem(ModBlocks.SET_WALL_DRIPSTONE_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cobbled_deepslate"), new BlockItem(ModBlocks.SET_WALL_COBBLED_DEEPSLATE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_polished_deepslate"), new BlockItem(ModBlocks.SET_WALL_POLISHED_DEEPSLATE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_tiles"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_TILES, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_deepslate_bricks"), new BlockItem(ModBlocks.SET_WALL_DEEPSLATE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_chiseled_deepslate"), new BlockItem(ModBlocks.SET_WALL_CHISELED_DEEPSLATE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cracked_deepslate_bricks"), new BlockItem(ModBlocks.SET_WALL_CRACKED_DEEPSLATE_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_cracked_deepslate_tiles"), new BlockItem(ModBlocks.SET_WALL_CRACKED_DEEPSLATE_TILES, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_smooth_basalt"), new BlockItem(ModBlocks.SET_WALL_SMOOTH_BASALT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_raw_iron_block"), new BlockItem(ModBlocks.SET_WALL_RAW_IRON_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_raw_copper_block"), new BlockItem(ModBlocks.SET_WALL_RAW_COPPER_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_raw_gold_block"), new BlockItem(ModBlocks.SET_WALL_RAW_GOLD_BLOCK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));

		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_mangrove_planks"), new BlockItem(ModBlocks.SET_WALL_MANGROVE_PLANKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_mangrove_log"), new BlockItem(ModBlocks.SET_WALL_MANGROVE_LOGS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_stripped_mangrove_log"), new BlockItem(ModBlocks.SET_WALL_STRIPPED_MANGROVE_LOGS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_mud"), new BlockItem(ModBlocks.SET_WALL_MUD, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_muddy_mangrove_roots"), new BlockItem(ModBlocks.SET_WALL_MUDDY_MANGROVE_ROOTS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_packed_mud"), new BlockItem(ModBlocks.SET_WALL_PACKED_MUD, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_mud_bricks"), new BlockItem(ModBlocks.SET_WALL_MUD_BRICKS, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_reinforced_deepslate"), new BlockItem(ModBlocks.SET_WALL_REINFORCED_DEEPSLATE, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_sculk"), new BlockItem(ModBlocks.SET_WALL_SCULK, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_sculk_catalyst"), new BlockItem(ModBlocks.SET_WALL_SCULK_CATALYST, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_ochre_froglight"), new BlockItem(ModBlocks.SET_WALL_OCHRE_FROGLIGHT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_verdant_froglight"), new BlockItem(ModBlocks.SET_WALL_VERDANT_FROGLIGHT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));
		Registry.register(Registry.ITEM, new Identifier("tvstudio", "set_wall_pearlescent_froglight"), new BlockItem(ModBlocks.SET_WALL_PEARLESCENT_FROGLIGHT, new FabricItemSettings().group(TvStudio.SET_WALL_GROUP)));

	}
}
